version: 2
services:
  - type: web
    name: your-app-name
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    routes:
      - src: /api/(.*)
        dest: /app.py
